<?php

/**
 * This is the model base class for the table "record".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Record".
 *
 * Columns in table "record" available as properties of the model,
 * followed by relations of table "record" available as properties of the model.
 *
 * @property integer $satelliteID
 * @property string $recordDate
 * @property integer $recordData
 *
 * @property Sattelite $sattelite
 */
abstract class BaseRecord extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'record';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Record|Records', $n);
	}

	public static function representingColumn() {
		return array(
			'satelliteID',
			'recordDate',
		);
	}

	public function rules() {
		return array(
			array('satelliteID, recordDate, recordData', 'required'),
			array('satelliteID, recordData', 'numerical', 'integerOnly'=>true),
			array('recordDate', 'length', 'max'=>11),
			array('satelliteID, recordDate, recordData', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'sattelite' => array(self::BELONGS_TO, 'Sattelite', 'satteliteID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'satelliteID' => Yii::t('app', 'Satellite'),
			'recordDate' => Yii::t('app', 'Record Date'),
			'recordData' => Yii::t('app', 'Record Data'),
			'sattelite' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('satelliteID', $this->satelliteID);
		$criteria->compare('recordDate', $this->recordDate, true);
		$criteria->compare('recordData', $this->recordData);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}