<?php

/**
 * This is the model base class for the table "planet".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Planet".
 *
 * Columns in table "planet" available as properties of the model,
 * followed by relations of table "planet" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $planetGSM
 * @property string $address
 * @property integer $NrSatellites
 * @property string $installDate
 * @property string $updateDate
 * @property string $extra1
 * @property string $extra2
 * @property integer $extra3
 * @property integer $extra4
 *
 * @property Group[] $groups
 * @property Satellite[] $satellites
 */
abstract class BasePlanet extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'planet';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Planet|Planets', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, planetGSM, address', 'required'),
			array('NrSatellites, extra3, extra4', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>100),
			array('planetGSM', 'length', 'max'=>20),
			array('address, extra1, extra2', 'length', 'max'=>45),
			array('installDate, updateDate', 'safe'),
			array('NrSatellites, installDate, updateDate, extra1, extra2, extra3, extra4', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, planetGSM, address, NrSatellites, installDate, updateDate, extra1, extra2, extra3, extra4', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'groups' => array(self::MANY_MANY, 'Group', 'planet_group(planet_id, group_id)'),
			'satellites' => array(self::HAS_MANY, 'Satellite', 'parentPlanetID'),
		);
	}

	public function pivotModels() {
		return array(
			'groups' => 'PlanetGroup',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'planetGSM' => Yii::t('app', 'Planet Gsm'),
			'address' => Yii::t('app', 'Address'),
			'NrSatellites' => Yii::t('app', 'Nr Satellites'),
			'installDate' => Yii::t('app', 'Install Date'),
			'updateDate' => Yii::t('app', 'Update Date'),
			'extra1' => Yii::t('app', 'Extra1'),
			'extra2' => Yii::t('app', 'Extra2'),
			'extra3' => Yii::t('app', 'Extra3'),
			'extra4' => Yii::t('app', 'Extra4'),
			'groups' => null,
			'satellites' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('planetGSM', $this->planetGSM, true);
		$criteria->compare('address', $this->address, true);
		$criteria->compare('NrSatellites', $this->NrSatellites);
		$criteria->compare('installDate', $this->installDate, true);
		$criteria->compare('updateDate', $this->updateDate, true);
		$criteria->compare('extra1', $this->extra1, true);
		$criteria->compare('extra2', $this->extra2, true);
		$criteria->compare('extra3', $this->extra3);
		$criteria->compare('extra4', $this->extra4);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}